# Generated by Django 4.2.3 on 2023-09-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='images/6+cart/jpg', max_length=200, null=True),
        ),
    ]
