# Generated by Django 4.2.3 on 2023-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='a',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
