# Generated by Django 4.2.3 on 2023-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='a',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to=''),
        ),
    ]
