# Generated by Django 4.2.3 on 2023-09-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_ordereditem_order_ordereditem_ordered_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='ordered_item',
            new_name='order',
        ),
    ]
