# Generated by Django 4.2.3 on 2023-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_ordered_item_ordereditem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
